version: "3.9"
services:
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "${NEXUS_PORT:-8081}:8081"
    volumes:
      - ${REMOTE_DATA_DIR:-/opt/swarm-data}/nexus-data:/nexus-data
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - public
networks:
  public:
    external: true
    name: ${OVERLAY_NETWORK_NAME:-public}


