version: "3.9"
services:
  nginx:
    image: nginx:stable
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ${REMOTE_DATA_DIR:-/opt/swarm-data}/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${REMOTE_DATA_DIR:-/opt/swarm-data}/nginx/certs:/etc/nginx/certs:ro
    # volumes:
    #   - ${REMOTE_DATA_DIR:-/opt/swarm-data}/nginx/conf.d:/etc/nginx/conf.d:ro
    #   - ${REMOTE_DATA_DIR:-/opt/swarm-data}/nginx/certs:/etc/nginx/certs:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
# networks:
#   public:
#     external: true
#     name: ${OVERLAY_NETWORK_NAME:-public}


